version: '3.1'

services:
  db-test:
    image: mysql
    build: ./MySQL_Init_Script/
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_USER: user
       MYSQL_PASSWORD: Your_password123
       MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata-test:/var/lib/mysql
      #- ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  integration:
    depends_on:
      - db-test
    image: "webshopapi:test-B${BUILD_NUMBER}"
    command: sh -c './wait-for.sh db-test:3306 -- dotnet test --verbosity=normal'
    build:
      context: .
      dockerfile: Dockerfile-Integration
volumes:
    dbdata-test: