version: '3.1'
 
services:
   db:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_USER: user
       MYSQL_PASSWORD: Your_password123
       MYSQL_ROOT_PASSWORD: secret
     volumes:
       - ./MySQL_Init_Script:/docker-entrypoint-initdb.d/
       - dbdata:/var/lib/mysql
     restart: always
 
   webshopapi:
     depends_on:
       - db
     image: webshopapi
     build:
       context: .
     command: sh -c './wait-for.sh db:3306 -- dotnet WebshopAPI.dll'
     ports:
       - "8081:80"
   
volumes:
   dbdata:
   MySQL_Init_Script:


